import { Cairo, Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Footer from "./Components/Footer/Footer";
import Footer1 from "./Components/FooterTest/Footer";
import Header from "./Components/Header/Header";

// Inter from Google Fonts
const cairo = Cairo({
  subsets: ["latin"],
  variable: "--font-cairo",
});

// Geist Fonts
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${cairo.variable} ${geistSans.variable} ${geistMono.variable} antialiased h-screen w-screen`}
      >
        <Header />
        {children}
        <Footer />
      </body>
    </html>
  );
}
